### ISSUE TITLE
slow paste

### ISSUE THREAD

**Issue by deathtrip** [IGI-111/Smith#28] opened 2020-03-10 00:51 UTC
The pasted text doesn't appear at once but in sequences. It's especially visible when pasting a few sentences or more.

**Comment by IGI-111** [comment] 2020-03-10 10:00
Hmm, could be an issue with the buffering, can you make sure that this still is noticeable when you run the release version?

**Comment by deathtrip** [comment] 2020-03-10 17:05
Not sure what you mean by release version, but i run the Arch Linux AUR version. Which installs using cargo.

**Comment by IGI-111** [comment] 2020-03-10 17:59
Alright so that is the release version.
Could you name the terminal emulator you're using? It might help me reproduce.

**Comment by deathtrip** [comment] 2020-03-10 19:58
I use terminator and konsole, and there is it slow.
Now i also checked alacritty and kitty, and they don't seem to have this problem.

**Comment by IGI-111** [comment] 2020-03-11 08:45
I use alacritty myself so I didn't notice a problem, but if it's terminal specific this is likely an issue with termion and/or how I use it. Will investigate further when I have the time.

**Comment by IGI-111** [comment] 2020-07-08 18:25
@deathtrip I'm closing this since this is most likely resolved by 2.0's double buffering.

**Closed by IGI-111** 2020-07-08 18:25 UTC
